# Generated by Django 4.2.2 on 2023-07-10 16:49

from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firtname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F')], max_length=9)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='personas/')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnosis', models.DateField()),
                ('sugar_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[patients.models.validate_even])),
                ('fat_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[patients.models.validate_even])),
                ('oxygen_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[patients.models.validate_even])),
                ('risk_level', models.CharField(blank=True, max_length=5, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
